server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: # kafka brokers
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      auto-offset-reset: earliest # consumer가 topic을 가져오는 순서, latest, earliest, none
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: com.illdangag.kafka.data
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
